### PR TITLE
Add type definition

### PR DESCRIPTION
**Pull request by kidonng**

### CODE REVIEW

**Comment by Mottie** [comment]
Thanks so much!

**Comment by fregante** [comment]
I don't think this is right. The types make it look like it's an ES Module. It should use `export = reservedNames`, where `reservedNames` is an `interface`

**Comment by kidonng** [comment]
> I don't think this is right. The types make it look like it's an ES Module. It should use `export = reservedNames`, where `reservedNames` is an `interface`

😥 Oh sorry, do you mean something like this?


```ts
interface reservedNames {
  all: string[];
  check(name: string): boolean;
  oddballs(): string[];
}

export = reservedNames;
```

I tried the type definition in this PR myself and it works fine, I didn't notice there is a difference between regular `export` and `export =`.

**Comment by Mottie** [comment]
Please provide a PR. I suck at TS.

**Comment by fregante** [comment]
@kidonng yes. The current type definition works if you have `esModulesInterop` enabled but it might fully work not otherwise. 

The documentation sucks at explaining this so I only know because of PRs I saw on Sindre Sorhus’ repos

**Comment by kidonng** [comment]
I did some experiments with the current type definition:

|                            | `import names from 'github-reserved-names'` | `import names = require('github-reserved-names')` |
| -------------------------- | ------------------------------------------- | ------------------------------------------------- |
| `"esModuleInterop": false` | ❌                                           | ✔                                                 |
| `"esModuleInterop": true`  | ✔                                           | ✔                                                 |

And when I use `interface` and `export =` TS complains about `names` is a type and should no be used as a value.

**Pull request merged**
